env_name: PickPlaceBread
expert_folder: human_demonstrations
robots: Panda
controller_type: JOINT_VELOCITY
total_timesteps: 1000000
batch_size: 256
robot_obs_keys:
  - robot0_joint_pos_cos
  - robot0_joint_pos_sin
obj_obs_keys:
  - Bread_to_robot0_eef_pos
  - robot0_eef_to_Bread_yaw
  - Bread_to_Bread_bin_pos
  - robot0_touch
lat_obs_dim: 4
lat_act_dim: 4
env_kwargs:
  horizon: 250
  gripper_types: 'PandaTouchGripper'
  use_touch_obs: True
  mount_type: null
evaluation:
  interval: 10000
  save_interval: 20000
seed: 42
save_buffer: False
logdir_prefix: null
suffix: BC
