env_name: TrackCube
robots: Panda
controller_type: JOINT_VELOCITY
robot_obs_keys:
  - robot0_joint_pos_cos
  - robot0_joint_pos_sin
obj_obs_keys:
  - target_to_robot0_eef_pos
lat_obs_dim: 4
lat_act_dim: 4
env_kwargs:
  horizon: 100
  table_full_size: [0.6, 0.6, 0.05]
  cube_init_pos_range: [-0.1, 0.1]
  ignore_done: True
  static_cube: True
num_episodes: 20
model_dir: logs/09.18.2024/19-56-52_Reach_Panda_JOINT_VELOCITY_BC/models/step_0140000
seed: 42
