env_name: Reach
env_kwargs:
  horizon: 50
  table_full_size: [0.6, 0.6, 0.05]
  mount_type: null
src_env:
  robot: Panda
  controller_type: JOINT_VELOCITY
  robot_obs_keys:
    - robot0_joint_pos_cos
    - robot0_joint_pos_sin
  obj_obs_keys:
    - target_to_robot0_eef_pos
tgt_env:
  robot: Panda
  controller_type: JOINT_VELOCITY
  robot_obs_keys:
    - robot0_joint_pos_cos
    - robot0_joint_pos_sin
  obj_obs_keys:
    - target_to_robot0_eef_pos
src_buffer: random_demos/Reach_200/Panda/JOINT_VELOCITY
tgt_buffer: random_demos/Reach_200/Sawyer/JOINT_VELOCITY
lat_obs_dim: 4
lat_act_dim: 4
tgt_align_timesteps: 2000000
batch_size: 512
src_model_dir: trained_models/AdjustedReachMedium/Panda_JV
seed: 42
save_buffer: False
logdir_prefix: null
log_freq: 1000
evaluation:
  interval: 2000
  save_interval: 20000
save_freq: 50000
suffix: align_initeefposfix
