env_name: Reach
robots: Panda
controller_type: JOINT_VELOCITY
robot_obs_keys:
  - robot0_joint_pos_cos
  - robot0_joint_pos_sin
obj_obs_keys:
  - target_to_robot0_eef_pos
lat_obs_dim: 4
lat_act_dim: 4
env_kwargs:
  horizon: 100
  table_full_size: [0.6, 0.6, 0.05]
  mount_type: null
  ignore_done: True
num_episodes: 10
model_dir: logs/09.20.2024/03-57-03_Reach_Panda_JOINT_VELOCITY_BC_initeefposfix_resetevery2/models/step_0980000
seed: 42